{% set name = "loris" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/loris-{{ version }}.tar.gz
  sha256: 2c77d110182e6bb78a7eeffc0d7dfbc3d56883bb26717cb05ac46cabc3091669

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # skipping osx as aedat is not available for osx yet
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
  run:
    - aedat
    - python
    - tqdm
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - loris
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neuromorphic-paris/loris
  summary: read and write files from neuromorphic cameras
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Tobias-Fischer
